import Main_Page from "./content";

export const metadata = {
  title: 'Mobile',
  description: 'Generated by create next app',
}
const MainPageDesktop = () => {
  return <Main_Page/>
}
export default MainPageDesktop